version: '3.3'

services:
   db:
     container_name: db     
     image: mysql:5.7
     ports:
       - "3306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: &rootPassword ijgw&#%@sssD
       MYSQL_DATABASE: grails
       MYSQL_USER: grails
       MYSQL_PASSWORD: &password toughPassword
